main: fix enum argument for init_emitter()
The function yaml_mapping_start_event_initialize()
takes yaml_mapping_style_t style as last argument:

int yaml_mapping_start_event_initialize(
	yaml_event_t *event,
	const yaml_char_t *anchor,
	const yaml_char_t *tag,
	int implicit,
	yaml_mapping_style_t style)

Use YAML_ANY_MAPPING_STYLE instead of YAML_ANY_SEQUENCE_STYLE. Both have
the same effective value of 0. No functional change.

Fix build error reported by GCC 10 with trace below:

main.c:173:5: error: implicit conversion from ‘enum yaml_sequence_style_e’ to ‘yaml_mapping_style_t’ {aka ‘enum yaml_mapping_style_e’} [-Werror=enum-conversion]
  173 |     YAML_ANY_SEQUENCE_STYLE))
      |     ^~~~~~~~~~~~~~~~~~~~~~~

Link: http://patchwork.ozlabs.org/project/buildroot/patch/20200530171428.562778-1-romain.naour@gmail.com/
Signed-off-by: Romain Naour <romain.naour@gmail.com>
[tweaked commit message and add link]
Signed-off-by: Etienne Carriere <etienne.carriere@linaro.org>